name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      serviceName:
        description: ECS Service Name
        default: flask-api
        required: true
      imageTag:
        description: Docker image tag
        default: latest
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password \
            | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Prepare vars
        run: |
          echo "SERVICE_NAME=${{ github.event.inputs.serviceName }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.event.inputs.imageTag }}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ github.event.inputs.serviceName }}:${{ github.event.inputs.imageTag }}" >> $GITHUB_ENV

      - name: Build + Push container
        run: |
          docker build -t $IMAGE_NAME ./api
          docker push $IMAGE_NAME

      - name: Install Pulumi
        run: curl -fsSL https://get.pulumi.com | sh
      - run: echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - working-directory: infra
        run: |
          pulumi login "s3://pulumi-state"
          pulumi stack init dev || true
          pulumi config set serviceName $SERVICE_NAME
          pulumi config set imageName $IMAGE_NAME
          pulumi up --yes
