name: Deploy to Azure

on:
  workflow_dispatch:
    inputs:
      serviceName:
        description: Azure Container App name
        default: flask-api
        required: true
      imageTag:
        description: Image tag
        default: latest
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare vars
        run: |
          echo "SERVICE_NAME=${{ github.event.inputs.serviceName }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.event.inputs.imageTag }}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}/${{ github.event.inputs.serviceName }}:${{ github.event.inputs.imageTag }}" >> $GITHUB_ENV

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.AZURE_REGISTRY_NAME }}

      - name: Build + Push container
        run: |
          docker build -t $IMAGE_NAME ./api
          docker push $IMAGE_NAME

      - name: Install Pulumi
        run: curl -fsSL https://get.pulumi.com | sh
      - run: echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

      - working-directory: infra
        run: |
          pulumi login --cloud-url "azblob://pulumi-state"
          pulumi stack init dev || true
          pulumi config set serviceName $SERVICE_NAME
          pulumi config set imageName $IMAGE_NAME
          pulumi up --yes
